# Generated by Django 3.0.4 on 2020-04-26 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
