# Generated by Django 3.0.4 on 2020-04-26 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
