# Generated by Django 3.0.4 on 2020-05-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('shirt_size', models.CharField(choices=[('Понедельник', (('10:00', '10:00'), ('12:00', '12:00'), ('15:00', '15:00'), ('17:00', '17:00'))), ('Вторник', (('10:00', '10:00'), ('12:00', '12:00'), ('15:00', '15:00'), ('17:00', '17:00'))), ('Среда', (('10:00', '10:00'), ('12:00', '12:00'), ('15:00', '15:00'), ('17:00', '17:00'))), ('Четверг', (('10:00', '10:00'), ('12:00', '12:00'), ('15:00', '15:00'), ('17:00', '17:00'))), ('Пятница', (('10:00', '10:00'), ('12:00', '12:00'), ('15:00', '15:00'), ('17:00', '17:00')))], max_length=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
