# Generated by Django 3.0.4 on 2020-05-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_auto_20200526_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Понедельник', (('Пн. 10:00', 'Пн. 10:00'), ('Пн. 12:00', 'Пн. 12:00'), ('Пн. 15:00', 'Пн. 15:00'), ('Пн. 17:00', 'Пн. 17:00'))), ('Вторник', (('Вт. 10:00', 'Вт. 10:00'), ('Вт. 12:00', 'Вт. 12:00'), ('Вт. 15:00', 'Вт. 15:00'), ('Вт. 17:00', 'Вт. 17:00'))), ('Среда', (('Ср. 10:00', 'Ср. 10:00'), ('Ср. 12:00', 'Ср. 12:00'), ('Ср. 15:00', 'Ср. 15:00'), ('Ср. 17:00', 'Ср. 17:00'))), ('Четверг', (('Чт. Пт.10:00', 'Чт. 10:00'), ('Чт. 12:00', 'Чт. 12:00'), ('Чт. 15:00', 'Чт. 15:00'), ('Чт. 17:00', 'Чт. 17:00'))), ('Пятница', (('Пт. 10:00', 'Пт. 10:00'), ('Пт. 12:00', 'Пт. 12:00'), ('Пт. 15:00', 'Пт. 15:00'), ('Пт. 17:00', 'Пт. 17:00')))], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Аккордеон', 'Аккордеон'), ('Гитара', 'Гитара'), ('Баян', 'Баян')], max_length=200, null=True),
        ),
    ]
