# Generated by Django 3.0.4 on 2020-05-02 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20200430_0342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=100)),
                ('teacher_age', models.CharField(max_length=50)),
                ('teacher_education', models.CharField(max_length=300)),
                ('teacher_information', models.CharField(max_length=600)),
            ],
        ),
    ]
