# Generated by Django 3.0.4 on 2020-05-02 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
