# Generated by Django 3.0.4 on 2020-05-02 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timetable',
        ),
    ]
