# Generated by Django 3.0.4 on 2020-05-14 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_timetable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timetable',
        ),
    ]
