# Generated by Django 3.0.4 on 2020-05-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_auto_20200526_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_age',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_surname',
            field=models.CharField(default='exit', max_length=30),
            preserve_default=False,
        ),
    ]
